sudo: false
language: node_js
node_js:
- '6'
env:
  global:
  - BROWSERSTACK_USERNAME: kitsonkelly1
  - BROWSERSTACK_ACCESS_KEY: uEoWrS6XmTX4XSpxUm6Q
install:
- travis_retry npm install grunt-cli
- travis_retry npm install
script:
- grunt dev
- grunt intern:node
- grunt intern:remote
- grunt remapIstanbul:ci
- grunt uploadCoverage
